### ISSUE TITLE
Can we use the wrapper toolbox for regression problem?

### ISSUE THREAD

**Issue by hanamthang** [JingweiToo/Wrapper-Feature-Selection-Toolbox#1]
Hello, 

Can we apply your code for any regression problem with continuous variables? 

Many thanks,
Thang

**Comment by JingweiToo** [comment]
Hi,

Yes, but you need to change the fitness function for your regression model.

**Comment by cy601** [comment]
Hello,
I am new to this field, Could you tell me what to do if I want to use another database and how can I use the ML-KNN classifier in this toolbox? 
Very thanks,
Tan Ngee

**Comment by JingweiToo** [comment]
The fitness function is using KNN (please refer to fitness function)

You can use another dataset but just make sure the format and the data structure are the same as the example provided. Please refer the input in the Readme
