### ISSUE TITLE
Can I use another classifiers in this Toolbox? 

### ISSUE THREAD

**Issue by cy601** [JingweiToo/Wrapper-Feature-Selection-Toolbox#2]
Oh, I know the fitness function uses KNN,.I have read some papers, most of them are using the  ML-KNN as fitness function. ML-knn is based on the KNN, but I don't know whether classification efficiency is improved. 
Thank you very much!

**Comment by JingweiToo** [comment]
Yes, you just change the code in the jFitnessFunction. You replace the KNN algorithm with yours.

**Comment by cy601** [comment]
OK thank you, let me have a try
