### ISSUE TITLE
plz solve the problem

### ISSUE THREAD

**Issue by ngcoolneha** [JingweiToo/Wrapper-Feature-Selection-Toolbox#4]
HI,
Everytime i run the algorithm for any of the feature selection method  ,i get diferrent feature set .....In that situation how can i get the optimal feature set .....Is it based on the acccuracy ????SUPPOSE I run PSO algorithm 10 times on same features and i get maximum accuracy with my 5th run...so that feature set will be optimal for my problem.

**Comment by JingweiToo** [comment]
Please use the random seed. If you read the papers and you will know the researchers will repeat the experiment 20 - 30 times then get the average.

**Comment by ngcoolneha** [comment]
Thanks
Actually I am new to feature selection methods....Should the researchers take  the **average of accuracy** with 20 and 30 runs....
Plz explain how can i use this Random seed.
