### ISSUE TITLE
can i use stratified  k fold cross validation in place of holdout cross validation

### ISSUE THREAD

**Issue by ngcoolneha** [JingweiToo/Wrapper-Feature-Selection-Toolbox#5]
hi
Can i use stratified  k fold cross validation in place of holdout cross validation in this algo..What changes should i make for doing it? I want to use 5 fold cross validation on my dataset  ...can u plz suggest me ....where should i can make changes in the algo.

**Comment by JingweiToo** [comment]
Yes, But you have to modify the fitness function.
