### ISSUE TITLE
can i change the population size???

### ISSUE THREAD

**Issue by ngcoolneha** [JingweiToo/Wrapper-Feature-Selection-Toolbox#6]
hi
IN this code u have taken population size opts.N as10 for data set 351X34 and my dataset is 126X125 ....with this datasize ,i can take no of solution as 10 or i need to change it....or what value i can take.......plz reply

**Comment by JingweiToo** [comment]
Hi, 

If you are not able to get a better result, then you may try to increase the population size and observe.
