### ISSUE TITLE
Update the examples

### ISSUE THREAD

**Issue by xRotor** [JingweiToo/Wrapper-Feature-Selection-Toolbox#7]
Dear Jingwei,
first of all, it's great that you have built this impressive toolbox and I really like to use it for research. However, I do not completely understand the examples you gave. Would it be possible to write a piece of stand-alone code with imports and a simple cost function that actually works? I don't know if it's just me, but I would then simply change the cost function to my own one and that's it. 
Thanks,
Fabian

**Comment by JingweiToo** [comment]
Hi, 

The toolbox will be used for feature selection but not for those unimodal, multi-modal functions. If you wish to do the uni-modal or multi-modal functions you may refer to another relevant project like https://github.com/thieu1995/mealpy. 

For this toolbox, the fitness function is writing in a standalone file.

**Comment by xRotor** [comment]
Hi,
Thanks for the quick reply. I'm not really sure what you mean by unimodal functions. I have a python method, that starts simulations and evaluations, and returns a fitness value for every set of parameters that it receives. I'd simply like to test different meta-heuristic algorithms with it. E.g., the python package "pyswarms" works like a charm. Where is that standalone file you mentioned and can it be modified?
Best regards,
Fabian

**Comment by xRotor** [comment]
Ah I'm sorry, its all matlab code. Though it was made for python. Issue can be close.

Edit: Your advice for  https://github.com/thieu1995/mealpy was great, so thanks again!
